import sys,re
import os; P=os.path.dirname(os.path.abspath(__file__))
s=open(''+os.path.join(P,'../../index.html')+'',encoding='utf-8').read()
s=s.replace('href="fuentes/','href="../fuentes/').replace('url("fuentes/','url("../fuentes/')
assert not re.search(r'(href|src)="fuentes/|url\("fuentes/',s)
import sys as _s; _s.path.insert(0,P); import motor; s=motor.aplicar(s)
capa=open(P+'/capa.html',encoding='utf-8').read(); js=open(P+'/capa.js.html',encoding='utf-8').read()
s=s.replace('</head>','<meta name="robots" content="noindex, nofollow">\n'+capa+'</head>',1)
s=s.replace('</body>',js+'</body>',1)
open(os.path.join(P,'../index.html'),'w',encoding='utf-8').write(s)
